# Generated by Django 2.2.5 on 2019-11-03 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='acive',
            new_name='active',
        ),
    ]
