# Generated by Django 2.2.5 on 2019-11-03 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_background'),
    ]

    operations = [
        migrations.DeleteModel(
            name='background',
        ),
    ]
